Save a copy in Drive of the given notebook and make changes.

Output for each of the questions is provided below each question. You need to produce the same output.

In [ ]:
import numpy as np

 1. Create a 4x6 numpy array filled with all zeros.

In [1]:
import numpy as np
arr= np.zeros((4, 6))
print(arr)

[[0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]]


2. Create a 5x5 numpy array filled with all ones.

In [ ]:
import numpy as np
ones_array = np.ones((5, 5))
print(ones_array)

[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]


3.Create an array of (4,5) filled with 4.

In [ ]:
import numpy as np
filled_array = np.full((4, 5), 4)
print(filled_array)

[[4 4 4 4 4]
 [4 4 4 4 4]
 [4 4 4 4 4]
 [4 4 4 4 4]]


For questions 4-13, consider the matrix

a=[[1,2,3],[1,4,5],[8,4,2]]


4. Write a code to get print the shape of the given matrix.




In [ ]:
import numpy as np
arr = np.array([[1, 2, 3], [1, 4, 5], [8, 4, 2]])
print(arr.shape)

(3, 3)


5.Write the code to print number of elements in a.

In [ ]:
import numpy as np
arr = np.array([[1, 2, 3], [1, 4, 5], [8, 4, 2]])
num_elements = arr.size
print(num_elements)

9


6. Print the 2nd row,1st column and element at (1,2) of a.

In [ ]:
import numpy as np

arr = np.array([[1, 2, 3], [1, 4, 5], [8, 4, 2]])

second_row = arr[1, :]

print(second_row)

first_column = arr[:, 0]

print(first_column)

element_1_2 = arr[1, 2]

print( element_1_2)

[1 4 5]
[1 1 8]
5


7. Change the element at (2,1) to 5.

In [2]:
import numpy as np

arr = np.array([[1, 2, 3], [1, 4, 5], [8, 4, 2]])

arr[2, 1] = 5

print(arr)

[[1 2 3]
 [1 4 5]
 [8 5 2]]


8. Print the first and the last element of the first row using stepsize approach.

In [3]:
import numpy as np

arr = np.array([[1, 2, 3], [1, 4, 5], [8, 4, 2]])

first_and_last = arr[0, ::len(arr[0])-1]

print(first_and_last)


[1 3]


9. Print the maximum and minimum values of a.

In [4]:
a = [[1, 2, 3], [1, 4, 5], [8, 4, 2]]

flatten_a = [val for row in a for val in row]
max_value = max(flatten_a)
min_value = min(flatten_a)

print( max_value)
print( min_value)

8
1


10. Print row-wise maximum values and their indicies of a.

In [9]:
a = [[1, 2, 3], [1, 4, 5], [8, 4, 2]]

for i, row in enumerate(a):
    max_value = max(row)
    max_index = row.index(max_value)
    print(max_value)
    print(max_index)


3
2
5
2
8
0


11. Divide all the elements of a by 4.

array([[0.25, 0.5 , 0.75],
       [0.25, 1.  , 1.25],
       [2.  , 1.25, 0.5 ]])

12. Sort a along the second axis.

array([[1, 2, 3],
       [1, 4, 5],
       [2, 5, 8]])

13. Print the indices that would sort a along the second axis.

array([[0, 1, 2],
       [0, 1, 2],
       [2, 1, 0]])

14. Create an identity matrix of size 6x6.

array([[1., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 1.]])

15. Let b=[1,4,3,2,6,8,5,4,2,0], split b into 3 arrays each of 3,4,3 elements.

[array([1, 4, 3]), array([2, 6, 8, 5]), array([4, 2, 0])]

16.Create a 1-D array of 40 evenly spaced elements between 0. and 1., inclusive.

[0.         0.02040816 0.04081633 0.06122449 0.08163265 0.10204082
 0.12244898 0.14285714 0.16326531 0.18367347 0.20408163 0.2244898
 0.24489796 0.26530612 0.28571429 0.30612245 0.32653061 0.34693878
 0.36734694 0.3877551  0.40816327 0.42857143 0.44897959 0.46938776
 0.48979592 0.51020408 0.53061224 0.55102041 0.57142857 0.59183673
 0.6122449  0.63265306 0.65306122 0.67346939 0.69387755 0.71428571
 0.73469388 0.75510204 0.7755102  0.79591837 0.81632653 0.83673469
 0.85714286 0.87755102 0.89795918 0.91836735 0.93877551 0.95918367
 0.97959184 1.        ]


17. Mutliply given arrays element-wise.

a=[[4,7,2],[1,3,9]]

b=[[1,5,0],[2,7,5]]

[[ 4 35  0]
 [ 2 21 45]]


18. Create a 3x2 array with random values from 0 to 1.

[[0.85271366 0.05800683]
 [0.52433678 0.17121163]
 [0.9743279  0.34707182]]
